openapi: 3.0.0
info:
  title: ecommerce-ms
  version: 1.0.0
  description: 'Product query API for the CAPITOLE application process'
tags:
  - name: Product
    description: Operations related to products
paths:
  /product/price:
    get:
      tags:
        - Product
      summary: Get applicable price for a product
      parameters:
        - name: applicationDate
          in: query
          required: true
          description: 'The date on which the tariff price for the product becomes effective or applicable. Format yyyy-MM-dd HH:mm:ss'
          schema:
            type: string
            format: date-time
            example: '2024-01-01 00:00:01'
        - name: productId
          in: query
          required: true
          description: 'Unique code or identifier assigned to a specific product.'
          schema:
            type: integer
            example: 1
        - name: brandId
          in: query
          required: true
          description: 'Identifier used to denote a brand to which a product.'
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponse'
        '400':
          description: Bad request (invalid or missing parameters)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '404':
          description: Price not found for the given parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
components:
  schemas:
    PriceResponse:
      type: object
      properties:
        productId:
          type: integer
          description: 'Unique code or identifier assigned to a specific product.'
          example: 1
        brandId:
          type: integer
          description: 'Identifier used to denote a brand to which a product.'
          example: 1
        startApplicationDate:
          type: string
          format: date-time
          description: 'Date on which the indicated rate price applies.  Format yyyy-MM-dd HH:mm:ss'
          example: '2024-01-01 00:00:01'
        endApplicationDate:
          type: string
          format: date-time
          description: 'Date on which the indicated rate price ends. Format yyyy-MM-dd HH:mm:ss'
          example: '2024-01-01 11:22:33'
        priceList:
          type: number
          description: 'Identifier of the applicable price rate.'
          example: 4
        finalPrice:
          type: number
          format: double
          description: 'Final sale price.'
          example: 22.34
    ApiErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          description: 'Date and time of the error'
          example: '2024-01-01 11:22:33'
        status:
          type: integer
          description: 'HTTP status code of the error'
        error:
          type: string
          description: 'Detailed error description'
        message:
          type: string
          description: 'Short error message'
        path:
          type: string
          description: 'Path of the request that generated the error'